title: Malware Analysis Center
author: Michael Lester
email: michael.lester.main@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A community tool for sharing and analyzing malware.
# social links
twitter_username: your-twitter-handle
github_username:  FusionCarcass

show_excerpts: true # set to false to remove excerpts on the homepage

github:
  is_project_page: true
  repository_url: http://example.com
  downloads_url: https://github.com/FusionCarcass/MalwareAnalysisCenter/releases/download/v0.9.1/Malware.Analysis.Center.msi

theme: jekyll-theme-cayman
