title: Malware Analysis Center
author: Michael Lester
email: michael.lester.main@gmail.com
description: A community tool for sharing and analyzing malware.
#twitter_username: your-twitter-handle
#github_username:  FusionCarcass
baseurl: /MalwareAnalysisCenter

show_excerpts: true # set to false to remove excerpts on the homepage

github:
  is_project_page: false

theme: jekyll-theme-cayman
